### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by pcg92** [0ximDigital/RxAnimations#10]
`java.lang.NoSuchMethodError: No virtual method lambda$call$1(Lrx/CompletableSubscriber;Landroid/support/v4/view/ViewPropertyAnimatorCompat;)V in class Loxim/digital/rxanim/AnimateOnSubscribe; or its super classes (declaration of 'oxim.digital.rxanim.AnimateOnSubscribe' appears in /data/app/package-app-2/split_lib_dependencies_apk.apk)
                                                                             at oxim.digital.rxanim.AnimateOnSubscribe$$Lambda$2.run(Unknown Source)
                                                                             at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
                                                                             at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
                                                                             at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)
                                                                             at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)`

**Comment by 0ximDigital** [comment]
Hi pcegarra,

Thanks for reporting this issue, I will take a look at it asap.

Can you please paste some code snippet that is causing this issue?
Thanks

**Comment by pcg92** [comment]
private void startAnimation(){
        final Subscription animateSubscription = RxAnimations.enterWithRotation(mLoading, 1000, 200, 200, 100, 80).subscribe();

    }

    buildToolsVersion "25.0.3"
    compile 'com.android.support:appcompat-v7:25.4.0'
    compile 'io.reactivex:rxjava:1.2.5'
    compile 'io.reactivex:rxandroid:1.2.1'

**Comment by pcg92** [comment]
Im using the android studio canary, maybe is a problem with retrolambda, I dont know..

**Comment by pcg92** [comment]
Yeah, the problem is retrolambda, I removed it and now its working
